const initialState = {

    products: [
        {
            id: 1,
            title: "Uni Pro",
            model: "Uni Pro",
            desc: "Home garage door",
            category: "Sectional doors",
            producer: "Wisniowski",
            price: "5000",
            amount: 1,
            color: "Ral 9016",
            width: 250,
            height: 225,
            img: "/images/products/sectional-doors/1/ral7016.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 2,
            title: "Uni Pro",
            model: "Uni Pro",
            desc: "Safe gate for your garage",
            category: "Sectional doors",
            producer: "Wisniowski",
            price: "5500",
            amount: 1,
            color: "Golden oak",
            width: 250,
            height: 225,
            img: "/images/products/sectional-doors/2/zlotydab.jpeg",
            sale: true,
            top: true,
        },
        {
            id: 3,
            title: "Uni Pro",
            model: "Uni Pro",
            desc: "The best product on market",
            category: "Sectional doors",
            producer: "Wisniowski",
            price: "5700",
            amount: 1,
            color: "Wallnut",
            width: 250,
            height: 225,
            img: "/images/products/sectional-doors/3/moodycoral.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 4,
            title: "Uni Pro",
            model: "Uni Pro",
            desc: "Safe and quiet in the garage",
            category: "Sectional doors",
            producer: "Wisniowski",
            price: "5000",
            amount: 1,
            color: "Ral 7016",
            width: 250,
            height: 225,
            img: "/images/products/sectional-doors/4/ral8014.jpeg",
            sale: false,
            top: false,
        },
        {
            id: 5,
            title: "Komfort garage door",
            model: "komfort",
            desc: "Up-and-over garage door",
            category: "Up-and-over doors",
            producer: "Wisniowski",
            price: "3200",
            amount: 1,
            color: "Ral 9016",
            width: 250,
            height: 225,
            img: "/images/products/up-and-over-doors/1/ral9016.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 6,
            title: "Komfort garage door",
            model: "Komfort",
            desc: "Safe and warm up-and-over garage door",
            category: "Up-and-over doors",
            producer: "Wisniowski",
            price: "3600",
            amount: 1,
            color: "Golden Oak",
            width: 250,
            height: 225,
            img: "/images/products/up-and-over-doors/2/orzech.jpeg",
            sale: false,
            top: true,
        },
        {
            id: 7,
            title: "Home Inclusive sliding gate",
            model: "AW 10.200",
            desc: "Raliable operation in any conditions",
            category: "Fences",
            producer: "Wisniowski",
            price: "12000",
            amount: 1,
            color: "RAL9005",
            width: 300,
            height: 150,
            img: "/images/products/fences/1/ral7030.jpeg",
            sale: false,
            top: true,
        },
        {
            id: 8,
            title: "Home Inclusive sliding gate",
            model: "AW 10.229",
            desc: "Automatic sliding gate is a great investment",
            category: "Fences",
            producer: "Wisniowski",
            price: "11500",
            amount: 1,
            color: "RAL9005",
            width: 300,
            height: 160,
            img: "/images/products/fences/2/ral9005.jpeg",
            sale: false,
            top: true,
        },
        {
            id: 9,
            title: "Classic sliding gate",
            model: "AW 10.72",
            desc: "Simple and modern design",
            category: "Fences",
            producer: "Wisniowski",
            price: "7000",
            amount: 1,
            color: "RAL9005",
            width: 300,
            height: 145,
            img: "/images/products/fences/3/ral7016.jpeg",
            sale: true,
            top: true,
        },
        {
            id: 10,
            title: "Modern double-leaf gate",
            model: "AW 10.105",
            desc: "Great solution for smaller fences",
            category: "Fences",
            producer: "Wisniowski",
            price: "6600",
            amount: 1,
            color: "RAL9005",
            width: 300,
            height: 145,
            img: "/images/products/fences/4/ral5010.jpeg",
            sale: false,
            top: false,
        },
        {
            id: 11,
            title: "Nova home doors",
            model: "016",
            desc: "Safe entrance to your home",
            category: "Doors",
            producer: "Wisniowski",
            price: "6900",
            amount: 1,
            color: "Flame Red",
            width: 91,
            height: 205,
            img: "/images/products/doors/1/flamered.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 12,
            title: "Nova home doors",
            model: "010",
            desc: "Warm and safe home doors",
            category: "Doors",
            producer: "Wisniowski",
            price: "5300",
            amount: 1,
            color: "RAL1003",
            width: 91,
            height: 205,
            img: "/images/products/doors/2/ral1003.jpeg",
            sale: true,
            top: true,
        },
        {
            id: 13,
            title: "Nova home doors",
            model: "029",
            desc: "Choose one of many colors",
            category: "Doors",
            producer: "Wisniowski",
            price: "10600",
            amount: 1,
            color: "Golden oak",
            width: 91,
            height: 205,
            img: "/images/products/doors/3/winchester.jpeg",
            sale: false,
            top: true,
        },
        {
            id: 14,
            title: "Eco industry doors",
            model: "Eco",
            desc: "Solid doors for industry",
            category: "Doors",
            producer: "Wisniowski",
            price: "1600",
            amount: 1,
            color: "RAL7035",
            width: 91,
            height: 205,
            img: "/images/products/doors/4/wenge.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 15,
            title: "Pulsar remote",
            model: "Pulsar",
            desc: "Simple remote controller",
            category: "Accessories",
            producer: "Wisniowski",
            price: "50",
            amount: 1,
            color: "Black",
            width: "",
            height: "",
            img: "/images/products/accessories/pulsar.jpeg",
            sale: false,
            top: true,
        },
        {
            id: 16,
            title: "Keypad",
            model: "Keypad",
            desc: "Safe access controller",
            category: "Accessories",
            producer: "Wisniowski",
            price: "600",
            amount: 1,
            color: "Black",
            width: "",
            height: "",
            img: "/images/products/accessories/keypad.jpeg",
            sale: false,
            top: false,
        },
        {
            id: 17,
            title: "Photocell",
            model: "Photocell",
            desc: "Take care about safety",
            category: "Accessories",
            producer: "Wisniowski",
            price: "200",
            amount: 1,
            color: "Black",
            width: '',
            height: "",
            img: "/images/products/accessories/fotocell.jpeg",
            sale: true,
            top: false,
        },
        {
            id: 18,
            title: "Battery",
            model: "Battery",
            desc: "Open garage door without electricity",
            category: "Accessories",
            producer: "Wisniowski",
            price: "300",
            amount: 1,
            color: "White",
            width: "",
            height: "",
            img: "/images/products/accessories/battery.jpeg",
            sale: false,
            top: true,
        },
    ],

    searchString: '',

    cart: {
      products: [],
    },

    user: null,

};  

export default initialState

